env:
  - CGO_ENABLED=0
before:
  hooks:
    - make
builds:
  - id: "{{cookiecutter.app_name}}"
    main: ./main.go
    binary: {{cookiecutter.app_name}}
    ldflags:
     - -s -w -X {{cookiecutter.app_server_host}}/{{cookiecutter.app_namespace}}/{{cookiecutter.app_name}}/cmd.version={{ '{{' }} .Version {{ '}}' }} -X {{cookiecutter.app_server_host}}/{{cookiecutter.app_namespace}}/{{cookiecutter.app_name}}/cmd.commit={{ '{{' }} .Commit {{ '}}' }} -X {{cookiecutter.app_server_host}}/{{cookiecutter.app_namespace}}/{{cookiecutter.app_name}}/cmd.date={{ '{{' }} .Date {{ '}}' }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
dockers:
 - binaries:
     - {{cookiecutter.app_name}}
   image_templates:
     - "{{cookiecutter.app_registry}}/{{cookiecutter.app_namespace}}/{{cookiecutter.app_name}}:latest"
     - "{{cookiecutter.app_registry}}/{{cookiecutter.app_namespace}}/{{cookiecutter.app_name}}:{{ '{{' }} .Tag {{ '}}' }}"
   dockerfile: Dockerfile.golang
archives:
  - replacements:
      amd64: x86_64
release:
  gitlab:
    owner: {{cookiecutter.app_namespace}}
    name: {{cookiecutter.app_name}}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ '{{' }} .Tag {{ '}}' }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
